import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService instance = LanguageService._();
  LanguageService._();
  String _lang = 'fr'; // fr | en
  String get lang => _lang;
  bool get isFr => _lang == 'fr';

  static const _key = 'app_lang';

  Future<void> init() async {
    final p = await SharedPreferences.getInstance();
    _lang = p.getString(_key) ?? 'fr';
    notifyListeners();
  }

  Future<void> toggle() async {
    _lang = _lang == 'fr' ? 'en' : 'fr';
    final p = await SharedPreferences.getInstance();
    await p.setString(_key, _lang);
    notifyListeners();
  }

  Future<void> setLang(String v) async {
    _lang = v;
    final p = await SharedPreferences.getInstance();
    await p.setString(_key, v);
    notifyListeners();
  }

  String t(String key) {
    return _translations[key]?[_lang] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'app_title': {'fr': 'SafeRide AI', 'en': 'SafeRide AI'},
    'home': {'fr': 'Accueil', 'en': 'Home'},
    'trips': {'fr': 'Trajets', 'en': 'Trips'},
    'map': {'fr': 'Carte', 'en': 'Map'},
    'profile': {'fr': 'Profil', 'en': 'Profile'},
    'assistance': {'fr': 'ASSISTANCE', 'en': 'SUPPORT'},
    'sos': {'fr': 'SOS URGENCE', 'en': 'SOS EMERGENCY'},
    'sos_desc': {'fr': 'Appuyez pour alerter vos contacts', 'en': 'Tap to alert your contacts'},
    'scan_qr': {'fr': 'Scanner un QR Code', 'en': 'Scan QR Code'},
    'scan_qr_desc': {'fr': 'Appuyez ici pour démarrer ou vérifier une course sécurisée.', 'en': 'Tap here to start or verify a secure ride.'},
    'scan_instruction': {'fr': 'Scannez le QR Code du\ntransporteur pour démarrer\nvotre trajet', 'en': 'Scan the driver\'s QR Code\nto start your ride'},
    'mode_scan_active': {'fr': 'Mode scan actif', 'en': 'Scan mode active'},
    'align_qr': {'fr': 'Alignez le QR code du transporteur', 'en': 'Align the driver QR code'},
    'services': {'fr': 'Mes services', 'en': 'My services'},
    'services_sub': {'fr': 'Trajet • Litige • Identité', 'en': 'Ride • Dispute • Identity'},
    'trip': {'fr': 'Trajet', 'en': 'Ride'},
    'trip_tracking': {'fr': 'Suivi GPS', 'en': 'GPS Tracking'},
    'dispute': {'fr': 'Litige', 'en': 'Dispute'},
    'dispute_sub': {'fr': 'Objets & SOS', 'en': 'Lost & SOS'},
    'identity': {'fr': 'Identité', 'en': 'Identity'},
    'identity_sub': {'fr': 'Vérifier', 'en': 'Verify'},
    'vehicle': {'fr': 'Véhicule', 'en': 'Vehicle'},
    'vehicle_qr': {'fr': 'QR unique', 'en': 'Unique QR'},
    'history': {'fr': 'Historique', 'en': 'History'},
    'history_full': {'fr': 'Voir l\'historique complet', 'en': 'View full history'},
    'login': {'fr': 'Se connecter', 'en': 'Sign in'},
    'register': {'fr': 'S\'inscrire', 'en': 'Sign up'},
    'logout': {'fr': 'Déconnexion', 'en': 'Sign out'},
    'guest': {'fr': 'Invité', 'en': 'Guest'},
    'guest_mode': {'fr': 'Mode invité — explorez librement. Inscrivez-vous pour interagir.', 'en': 'Guest mode — explore freely. Sign up to interact.'},
    'guest_locked': {'fr': 'Fonctionnalité verrouillée — inscrivez-vous', 'en': 'Feature locked — sign up'},
    'welcome': {'fr': 'Bienvenue sur SafeRide AI', 'en': 'Welcome to SafeRide AI'},
    'welcome_sub': {'fr': 'Rejoignez SafeRide AI pour des trajets sécurisés.', 'en': 'Join SafeRide AI for secure rides.'},
    'hello': {'fr': 'Bonjour', 'en': 'Hello'},
    'verified_secure': {'fr': 'VOTRE COMPTE EST VÉRIFIÉ ET SÉCURISÉ', 'en': 'YOUR ACCOUNT IS VERIFIED AND SECURE'},
    'verified_carrier': {'fr': 'VOTRE COMPTE TRANSPORTEUR EST VÉRIFIÉ', 'en': 'YOUR DRIVER ACCOUNT IS VERIFIED'},
    'email': {'fr': 'Adresse e-mail', 'en': 'Email address'},
    'password': {'fr': 'Mot de passe', 'en': 'Password'},
    'email_hint': {'fr': 'jean.dupont@exemple.com', 'en': 'john.doe@example.com'},
    'phone': {'fr': 'Téléphone', 'en': 'Phone'},
    'name': {'fr': 'Nom complet', 'en': 'Full name'},
    'first_name': {'fr': 'Prénom', 'en': 'First name'},
    'or_continue': {'fr': 'OU CONTINUER AVEC', 'en': 'OR CONTINUE WITH'},
    'no_account': {'fr': 'Pas de compte ? ', 'en': 'No account? '},
    'has_account': {'fr': 'Déjà inscrit ? Se connecter', 'en': 'Already have an account? Sign in'},
    'continue_guest': {'fr': 'Continuer en tant qu\'invité — explorer', 'en': 'Continue as guest — explore'},
    'guest_info': {'fr': 'Visiteur : consultez toutes les fonctionnalités. L\'interaction nécessite une inscription.', 'en': 'Visitor: browse all features. Interaction requires sign up.'},
    'forgot_password': {'fr': 'Mot de passe oublié ?', 'en': 'Forgot password?'},
    'create_account': {'fr': 'Créer un compte', 'en': 'Create account'},
    'create_account_btn': {'fr': 'Créer mon compte', 'en': 'Create my account'},
    'accept_terms': {'fr': 'J\'accepte les Conditions d\'utilisation et la Politique de confidentialité', 'en': 'I accept the Terms and Privacy Policy'},
    'you_are': {'fr': 'Vous êtes :', 'en': 'You are:'},
    'passenger': {'fr': 'Passager', 'en': 'Passenger'},
    'driver': {'fr': 'Transporteur', 'en': 'Driver'},
    'searching': {'fr': 'Je cherche', 'en': 'I need a ride'},
    'offering': {'fr': 'Je propose', 'en': 'I offer rides'},
    'translate_tooltip': {'fr': 'Langue : Français ↔ English', 'en': 'Language: English ↔ French'},
    'language': {'fr': 'Français', 'en': 'English'},
    'notifications': {'fr': 'Notifications', 'en': 'Notifications'},
    'my_qr': {'fr': 'Mon QR Code', 'en': 'My QR Code'},
    'present_qr': {'fr': 'Présentez ce QR au passager pour démarrer la course', 'en': 'Show this QR to the passenger to start the ride'},
    'qr_active': {'fr': 'QR actif • régénération auto après chaque scan', 'en': 'QR active • auto-regenerates after each scan'},
    'no_vehicle': {'fr': 'Aucun véhicule', 'en': 'No vehicle'},
    'add_vehicle': {'fr': 'Ajouter mon véhicule', 'en': 'Add my vehicle'},
    'dashboard': {'fr': 'Tableau de bord', 'en': 'Dashboard'},
    'stats_notes': {'fr': 'Stats & notes', 'en': 'Stats & ratings'},
    'hearing_course': {'fr': 'Course', 'en': 'Ride'},
    'auto_listening': {'fr': 'Écoute auto', 'en': 'Auto listening'},
    // --- Added keys ---
    'signup_required': {'fr': 'Inscription requise', 'en': 'Registration required'},
    'visitor_restricted_msg': {'fr': 'Visiteur — vous pouvez consulter toutes les fonctionnalités, mais pour interagir avec le système (scanner, SOS, signaler, etc.), veuillez vous inscrire.', 'en': 'Visitor — you can browse all features, but to interact (scan, SOS, report, etc.), please sign up.'},
    'stay_as_guest': {'fr': 'Rester en visite', 'en': 'Stay as guest'},
    'sos_confirm_msg': {'fr': 'Déclencher une alerte SOS manuelle ?\nVos contacts d\'urgence, le gestionnaire et les services seront notifiés avec votre position.', 'en': 'Trigger a manual SOS alert?\nYour emergency contacts, manager and services will be notified with your location.'},
    'cancel': {'fr': 'Annuler', 'en': 'Cancel'},
    'trigger_sos': {'fr': 'Déclencher SOS', 'en': 'Trigger SOS'},
    'no_active_trip_scan': {'fr': 'Aucun trajet actif — scannez le QR pour démarrer un trajet', 'en': 'No active ride — scan QR to start a ride'},
    'location_permission_denied': {'fr': 'Permission localisation refusée', 'en': 'Location permission denied'},
    'sos_triggered': {'fr': 'SOS manuel déclenché ✓ — contacts notifiés', 'en': 'Manual SOS triggered ✓ — contacts notified'},
    'location_unavailable': {'fr': 'Localisation indisponible', 'en': 'Location unavailable'},
    'locating': {'fr': 'Localisation en cours…', 'en': 'Locating…'},
    'map_credits': {'fr': 'Cartes © OpenStreetMap', 'en': 'Maps © OpenStreetMap'},
    'my_location': {'fr': 'Ma position', 'en': 'My location'},
    'weather_loading': {'fr': 'Chargement de la météo…', 'en': 'Loading weather…'},
    'qr_unavailable': {'fr': 'QR indisponible', 'en': 'QR unavailable'},
    'add_vehicle_hint': {'fr': 'Ajoutez votre véhicule unique pour générer le QR', 'en': 'Add your unique vehicle to generate QR'},
    'qr_regenerated': {'fr': 'QR régénéré après scan !', 'en': 'QR regenerated after scan!'},
    'guest_consult_text': {'fr': 'Consultez toutes les fonctionnalités. L\'interaction nécessite un compte.', 'en': 'Browse all features. Interaction requires an account.'},
    'yaounde_map': {'fr': 'Yaoundé • Carte', 'en': 'Yaoundé • Map'},
    'services_preview': {'fr': 'Aperçu des services', 'en': 'Services preview'},
    'lost_and_sos': {'fr': 'Objets perdus & SOS', 'en': 'Lost & Found & SOS'},
    'cni_passport': {'fr': 'CNI / Passeport', 'en': 'ID / Passport'},
    'vehicles': {'fr': 'Véhicules', 'en': 'Vehicles'},
    'vehicle_qr_label': {'fr': 'QR transporteur', 'en': 'Driver QR'},
    'stats_carrier': {'fr': 'Stats transporteur', 'en': 'Driver stats'},
    'create_account_interact': {'fr': 'Créer mon compte — interagir', 'en': 'Create my account — interact'},
    'email_required': {'fr': 'Email requis', 'en': 'Email required'},
    'password_required': {'fr': 'Mot de passe requis', 'en': 'Password required'},
    'contact_support_reset': {'fr': 'Contactez le support pour réinitialiser votre mot de passe : support@saferide.app', 'en': 'Contact support to reset your password: support@saferide.app'},
    'phone_required': {'fr': 'Téléphone requis', 'en': 'Phone required'},
    'name_required': {'fr': 'Nom requis', 'en': 'Name required'},
    'first_name_required': {'fr': 'Prénom requis', 'en': 'First name required'},
    'min_8_chars': {'fr': 'Minimum 8 caractères', 'en': 'Minimum 8 characters'},
    'strength_weak': {'fr': 'Force : Faible', 'en': 'Strength: Weak'},
    'step_1_of_3': {'fr': 'Étape 1/3', 'en': 'Step 1/3'},
    'accept_terms_required': {'fr': 'Veuillez accepter les Conditions d\'utilisation et la Politique de confidentialité', 'en': 'Please accept the Terms and Privacy Policy'},
    'or_register_with': {'fr': 'OU S\'INSCRIRE AVEC', 'en': 'OR SIGN UP WITH'},
    'permission_camera_denied': {'fr': 'Permission caméra refusée', 'en': 'Camera permission denied'},
    'enable_camera_settings': {'fr': 'Activez la caméra dans Paramètres pour scanner le QR', 'en': 'Enable camera in Settings to scan QR'},
    'retry': {'fr': 'Réessayer', 'en': 'Retry'},
    'torch': {'fr': 'Torche', 'en': 'Torch'},
    'no_trip': {'fr': 'Aucun trajet en cours', 'en': 'No ride in progress'},
    'no_trip_body': {'fr': 'Aucun trajet actif', 'en': 'No active ride'},
    'no_trip_sos_msg': {'fr': 'Le SOS est lié à un trajet en cours : scannez le QR du transporteur pour démarrer un trajet avant de déclencher une alerte.', 'en': 'SOS is linked to an active ride: scan the driver QR to start a ride before triggering an alert.'},
    'see_current_trip': {'fr': 'Voir mon trajet en cours', 'en': 'View my current ride'},
    'trip_title': {'fr': 'Trajet', 'en': 'Ride'},
    'trip_finished': {'fr': 'Trajet terminé', 'en': 'Ride finished'},
    'confirm_boarding': {'fr': 'Confirmer l\'embarquement', 'en': 'Confirm boarding'},
    'boarding_pending': {'fr': 'QR scanné — embarquement en attente', 'en': 'QR scanned — boarding pending'},
    'confirm_your_boarding': {'fr': 'Confirmez votre embarquement dans ce véhicule :', 'en': 'Confirm your boarding in this vehicle:'},
    'enter_destination': {'fr': 'Saisissez votre destination :', 'en': 'Enter your destination:'},
    'propose_destination': {'fr': 'Proposer la destination', 'en': 'Propose destination'},
    'destination_proposed': {'fr': 'Destination proposée', 'en': 'Destination proposed'},
    'is_destination_correct': {'fr': 'Votre destination est-elle correcte ?', 'en': 'Is your destination correct?'},
    'yes_confirm': {'fr': 'Oui, confirmer', 'en': 'Yes, confirm'},
    'no_edit': {'fr': 'Non, la modifier', 'en': 'No, edit it'},
    'end_trip': {'fr': 'Fin de trajet', 'en': 'End ride'},
    'processing': {'fr': 'Traitement...', 'en': 'Processing...'},
    'send_location': {'fr': 'Envoyer la position', 'en': 'Send location'},
    'offline_banner': {'fr': 'En attente de connexion', 'en': 'Waiting for connection'},
    'sync_in_progress': {'fr': 'Synchronisation en cours', 'en': 'Sync in progress'},
    'identity_verification': {'fr': 'Vérification d\'identité', 'en': 'Identity verification'},
    'current_status': {'fr': 'Statut actuel', 'en': 'Current status'},
    'document_type': {'fr': 'Type de document', 'en': 'Document type'},
    'document_number_optional': {'fr': 'Numéro du document (optionnel)', 'en': 'Document number (optional)'},
    'recto_required': {'fr': 'Recto de la carte (obligatoire)', 'en': 'Front of card (required)'},
    'verso_required': {'fr': 'Verso de la carte (obligatoire)', 'en': 'Back of card (required)'},
    'selfie_required': {'fr': 'Selfie avec pièce en main (obligatoire)', 'en': 'Selfie holding ID (required)'},
    'selfie_hint': {'fr': 'Tenez votre CNI / passeport à côté de votre visage, bien visible.', 'en': 'Hold your ID next to your face, clearly visible.'},
    'submit_verification': {'fr': 'Soumettre la vérification (3 photos)', 'en': 'Submit verification (3 photos)'},
    'provide_3_photos': {'fr': 'Veuillez fournir les 3 photos : recto, verso et selfie avec pièce en main (obligatoires).', 'en': 'Please provide the 3 photos: front, back and selfie holding ID (required).'},
    'camera': {'fr': 'Caméra', 'en': 'Camera'},
    'gallery': {'fr': 'Galerie', 'en': 'Gallery'},
    'lost_item': {'fr': 'Objet perdu', 'en': 'Lost item'},
    'my_reports': {'fr': 'Mes signalements', 'en': 'My reports'},
    'report': {'fr': 'Signaler', 'en': 'Report'},
    'no_report_yet': {'fr': 'Aucun signalement pour le moment', 'en': 'No reports yet'},
    'chronology': {'fr': 'Chronologie', 'en': 'Chronology'},
    'concerned_trip': {'fr': 'Trajet concerné', 'en': 'Concerned ride'},
    'choose_finished_trip': {'fr': 'Choisir un trajet terminé', 'en': 'Choose a completed ride'},
    'loading': {'fr': 'Chargement…', 'en': 'Loading…'},
    'forgotten_item': {'fr': 'Objet oublié', 'en': 'Forgotten item'},
    'description_optional': {'fr': 'Description (facultatif)', 'en': 'Description (optional)'},
    'report_lost_item': {'fr': 'Signaler l\'objet perdu', 'en': 'Report lost item'},
    'choose_trip': {'fr': 'Choisissez un trajet', 'en': 'Choose a ride'},
    'describe_forgotten_item': {'fr': 'Décrivez l\'objet oublié', 'en': 'Describe the forgotten item'},
    'disputes': {'fr': 'Litiges', 'en': 'Disputes'},
    'my_disputes': {'fr': 'Mes litiges', 'en': 'My disputes'},
    'open': {'fr': 'Ouvrir', 'en': 'Open'},
    'no_dispute_yet': {'fr': 'Aucun litige pour le moment', 'en': 'No disputes yet'},
    'open_dispute': {'fr': 'Ouvrir le litige', 'en': 'Open dispute'},
    'motive': {'fr': 'Motif', 'en': 'Reason'},
    'close': {'fr': 'Fermer', 'en': 'Close'},
    'delete': {'fr': 'Supprimer', 'en': 'Delete'},
    'add': {'fr': 'Ajouter', 'en': 'Add'},
    'replace': {'fr': 'Remplacer', 'en': 'Replace'},
    'replace_vehicle': {'fr': 'Remplacer le véhicule', 'en': 'Replace vehicle'},
    'add_vehicle_title': {'fr': 'Ajouter un véhicule', 'en': 'Add a vehicle'},
    'single_vehicle_warning': {'fr': 'Un seul véhicule autorisé. L\'ancien sera remplacé.', 'en': 'Only one vehicle allowed. The old one will be replaced.'},
    'brand': {'fr': 'Marque', 'en': 'Brand'},
    'model': {'fr': 'Modèle', 'en': 'Model'},
    'registration': {'fr': 'Immatriculation', 'en': 'Registration'},
    'type': {'fr': 'Type', 'en': 'Type'},
    'moto': {'fr': 'Moto', 'en': 'Motorbike'},
    'car': {'fr': 'Voiture', 'en': 'Car'},
    'minibus': {'fr': 'Minibus', 'en': 'Minibus'},
    'bus': {'fr': 'Bus', 'en': 'Bus'},
    'my_unique_vehicle': {'fr': 'Mon véhicule (unique)', 'en': 'My vehicle (unique)'},
    'my_vehicle': {'fr': 'Mon véhicule', 'en': 'My vehicle'},
    'no_vehicle_add_unique': {'fr': 'Aucun véhicule. Ajoutez votre véhicule unique.', 'en': 'No vehicle. Add your unique vehicle.'},
    'show_qr': {'fr': 'Afficher le QR', 'en': 'Show QR'},
    'delete_vehicle_confirm': {'fr': 'Supprimer le véhicule', 'en': 'Delete vehicle'},
    'delete_vehicle_msg': {'fr': 'Un transporteur doit conserver au moins un véhicule. Si vous avez un seul véhicule, la suppression sera refusée. Confirmer ?', 'en': 'Driver must keep at least one vehicle. If you have only one, deletion will be denied. Confirm?'},
    'vehicle_deleted': {'fr': 'Véhicule supprimé', 'en': 'Vehicle deleted'},
    'no_active_qr': {'fr': 'Aucun QR actif pour ce véhicule', 'en': 'No active QR for this vehicle'},
    'qr_auto_regen': {'fr': 'Ce QR se régénère automatiquement après chaque scan.', 'en': 'This QR auto-regenerates after each scan.'},
    'regenerate_qr': {'fr': 'Régénérer le QR', 'en': 'Regenerate QR'},
    'qr_regenerated_simple': {'fr': 'QR régénéré !', 'en': 'QR regenerated!'},
    'history_trips': {'fr': 'Historique des trajets', 'en': 'Ride history'},
    'view_recent_trips': {'fr': 'Consultez vos trajets récents', 'en': 'View your recent rides'},
    'today': {'fr': 'Aujourd\'hui', 'en': 'Today'},
    'this_week': {'fr': 'Cette semaine', 'en': 'This week'},
    'no_finished_trip': {'fr': 'Aucun trajet terminé', 'en': 'No completed rides'},
    'details': {'fr': 'Détails', 'en': 'Details'},
    'terminated': {'fr': 'TERMINÉ', 'en': 'COMPLETED'},
    'save': {'fr': 'Enregistrer', 'en': 'Save'},
    'save_info': {'fr': 'Enregistrer les informations', 'en': 'Save information'},
    'personal_info': {'fr': 'Informations personnelles', 'en': 'Personal information'},
    'security_word': {'fr': 'Mot de sécurité', 'en': 'Security word'},
    'emergency_contacts': {'fr': 'Gestion Contacts Urgence', 'en': 'Emergency Contacts'},
    'history_trips_menu': {'fr': 'Historique des trajets', 'en': 'Ride history'},
    'support_ai': {'fr': 'Support • Assistant IA', 'en': 'Support • AI Assistant'},
    'verify_identity': {'fr': 'Vérification d\'identité', 'en': 'Identity verification'},
    'voice_recognition': {'fr': 'Reconnaissance vocale', 'en': 'Voice recognition'},
    'settings_saved': {'fr': 'Paramètres enregistrés', 'en': 'Settings saved'},
    'sos_manual_tooltip': {'fr': 'SOS manuel — appui pour déclencher', 'en': 'Manual SOS — tap to trigger'},
    'permission_gallery_denied': {'fr': 'Permission galerie refusée', 'en': 'Gallery permission denied'},
    'permission_mic_required': {'fr': 'Permission microphone requise', 'en': 'Microphone permission required'},
    'photo_ready': {'fr': 'Prêt', 'en': 'Ready'},
    'front': {'fr': 'Recto', 'en': 'Front'},
    'back': {'fr': 'Verso', 'en': 'Back'},
    'selfie_plus_id': {'fr': 'Selfie + pièce', 'en': 'Selfie + ID'},
    'front_clear': {'fr': 'Face avant claire', 'en': 'Clear front side'},
    'back_clear': {'fr': 'Face arrière claire', 'en': 'Clear back side'},
    'face_plus_doc': {'fr': 'Visage + document (direct)', 'en': 'Face + document (live)'},
    'in_danger': {'fr': 'Vous êtes en danger ?', 'en': 'Are you in danger?'},
    'hold_to_trigger_sos': {'fr': 'Maintenez le bouton pour déclencher une alerte SOS transmise à vos contacts d\'urgence, au gestionnaire et aux services d\'urgence.', 'en': 'Hold the button to trigger an SOS alert sent to your emergency contacts, manager and emergency services.'},
    'long_press': {'fr': 'Appui long', 'en': 'Long press'},
    'use_voice_trigger': {'fr': 'Utiliser le déclenchement vocal', 'en': 'Use voice trigger'},
    'configure_voice_sos': {'fr': 'Configurer le SOS vocal', 'en': 'Configure voice SOS'},
    'voice_sos_desc': {'fr': 'Définissez un mot de sécurité puis enrôlez votre voix en 3 prises. Au déclenchement, dites ce mot : mot-clé + biométrie vocale vérifiés avant l\'alerte.', 'en': 'Set a security word then enroll your voice in 3 takes. On trigger, say this word: keyword + voice biometrics verified before alert.'},
    'security_word_hint': {'fr': 'Mot de sécurité (3-40 caractères)', 'en': 'Security word (3-40 characters)'},
    'enroll_voice_profile': {'fr': 'Enrôler mon profil vocal', 'en': 'Enroll my voice profile'},
    'voice_trigger_title': {'fr': 'Déclenchement vocal', 'en': 'Voice trigger'},
    'say_security_word': {'fr': 'Dites votre mot de sécurité', 'en': 'Say your security word'},
    'to_alert': {'fr': 'pour alerter.', 'en': 'to alert.'},
    'speak': {'fr': 'Parler', 'en': 'Speak'},
    'listening': {'fr': 'Écoute…', 'en': 'Listening…'},
    'heard': {'fr': 'Entendu', 'en': 'Heard'},
    'fallback_sos_button': {'fr': 'Fallback : bouton SOS', 'en': 'Fallback: SOS button'},
    'trip_no_destination': {'fr': 'Trajet sans destination', 'en': 'Ride without destination'},
  };
}
